### ISSUE TITLE
Utilise folder structure in SASS

### ISSUE THREAD

**Issue by jakejackson1** [GravityPDF/gravity-pdf-bulk-generator#25]
Instead of adding underscores to the beginning of filenames (not sure what that means), can we use folders to better structure these files?

**Comment by debbieellis7** [comment]
_ is a pretty standard way with Sass to denote that the file is not a whole structure but instead a partial of a larger whole. In our case it's the main.scss

**Comment by debbieellis7** [comment]
It’s not just a convention but a feature by SASS called partials. Files beginning with an underscore won’t be compiled stand-alone and therefore don’t generate any file in dist.

**Comment by jakejackson1** [comment]
Any issue putting partials in folders?

**Comment by debbieellis7** [comment]
This is just a small plugin @jakejackson1 and I think it's a total overkill. So I named it as what it represent.

**Comment by jakejackson1** [comment]
Every project starts out small. The problems occur when you have to pay off technical debt when they grow larger. If we plan ahead to grow we have less debt to payoff and an easier time of it. The names of the files are fine, I'd just like to group them into a logical folder(s).
