### ISSUE TITLE
Missing 'Download PDF' Option from the Dropdown Menu

### ISSUE THREAD

**Issue by mcglenn07** [GravityPDF/gravity-pdf-bulk-generator#85]
When clicking Entries from the Dashboard under Forms, Download PDF option is missing initially. I would then have to click the Entries under the Form Title to make that option appear.

**Comment by debbieellis7** [comment]
Please provide screenshot @mcglenn07. Thanks!

**Comment by mcglenn07** [comment]
![image](https://user-images.githubusercontent.com/35588091/79393778-9c325900-7fa8-11ea-8cc0-1fa82c5b7d78.png)

**Comment by mcglenn07** [comment]
![image](https://user-images.githubusercontent.com/35588091/79393842-bc621800-7fa8-11ea-8f92-4f8a9c10b415.png)
